name: GoreaParty
author: GoreaCraft
main: com.goreacraft.plugins.goreaparty.Main
version: 1.3
website: http://www.goreacraft.com
description: Best plugin!
commands:
  goreaparty: 
    aliases: [party, p, gparty]  
    description: GoreaCraft version of party plugin!
    default: false
    usage: More info on '/party help'

  

